gateway:
  oauth:
    issuer: 
    client-id: 
spring:
  security.oauth2.resourceserver.jwt.issuer-uri: ${gateway.oauth.issuer}
  cloud.gateway:  
    routes:
    - id: frontend
      uri: http://frontend.default
      predicates:
      - Path=/frontend/**
      filters:
      - StripPrefix=1
      - RewriteResponseBody=enabled\:!1,issuer\:"",clientId\:"":enabled\:!0,issuer\:"${gateway.oauth.issuer}",clientId\:"${gateway.oauth.client-id}"  