gateway:
  oauth:
    issuer:
      host: login.microsoftonline.com/29248f74-371f-4db2-9a50-c62a6877a0c1
      scheme: https
    client-id: d833fd59-c991-44f9-bdcd-5423ac27b9ca
spring:
  security.oauth2.resourceserver.jwt.issuer-uri: ${gateway.oauth.issuer.scheme}://${gateway.oauth.issuer.host}/discovery/v2.0/keys
  cloud.gateway:  
    discovery.locator.enabled: false
    routes:
    - id: product-service
      uri: lb://PRODUCT-SERVICE
      predicates:
      - Path=/services/product-service/**
      filters:
      - StripPrefix=2
    - id: order-service
      uri: lb://ORDER-SERVICE
      predicates:
      - Path=/services/order-service/**
      filters:
      - StripPrefix=2
    - id: frontend
      uri: http://frontend.default
      predicates:
      - Path=/frontend/**
      filters:
      - StripPrefix=1
      - RewriteResponseBody=ISSUER_SCHEME:{gateway.oauth.issuer.scheme},ISSUER_HOST:${gateway.oauth.issuer.host},CLIENT_ID_VALUE:${gateway.oauth.client-id},strictDiscoveryDocumentValidation=!0:strictDiscoveryDocumentValidation=0,skipIssuerCheck=!1:skipIssuerCheck=1,\+this.getAccessToken:\+this.getIdToken,this.oAuthService.getAccessToken:this.oAuthService.getIdToken
    globalcors.corsConfigurations:
      '[/**]':
        allowedOrigins:
          - "*"
        allowedMethods:
          - "*"
        allowedHeaders:
          - "*"    