spring:
  cloud:
    stream:
      bindings:
        shipOrder-in-0.destination: ${shipping.in-queue}
        shipOrder-out-0.destination: ${shipping.out-queue}
      servicebus.bindings:
        shipOrder-out-0.producer.entity-type: queue
  endpoint:
    restart.enabled: true
    env.show-values: ALWAYS
  endpoints.web.exposure.include: "*"
shipping:
  servicebus-fqn: servicebus.windows.net
  in-queue: order-shipping-queue
  out-queue: order-delivered-queue
  duration: 10000