LOCAL_PATH = os.getenv("LOCAL_PATH", default='.')
NAMESPACE = os.getenv("NAMESPACE", default='default')
OUTPUT_TO_NULL_COMMAND = os.getenv("OUTPUT_TO_NULL_COMMAND", default=' > /dev/null ')
if os.getenv("SOURCE_IMAGE"):
  OPTIONAL_SOURCE_IMAGE_FLAG=" --source-image " + os.getenv("SOURCE_IMAGE")
else:
  OPTIONAL_SOURCE_IMAGE_FLAG=""

k8s_custom_deploy(
  'product-service',
  apply_cmd="tanzu apps workload apply -f config/workload.yaml --debug --live-update" +
    " --local-path " + LOCAL_PATH +
    OPTIONAL_SOURCE_IMAGE_FLAG +
    " --label apps.tanzu.vmware.com/has-tests-" +
    " --namespace " + NAMESPACE +
    " --yes " +
    OUTPUT_TO_NULL_COMMAND + 
    " && kubectl get workload product-service --namespace " + NAMESPACE + " -o yaml",
  delete_cmd="tanzu apps workload delete -f config/workload.yaml --namespace " + NAMESPACE + " --yes" ,
  deps=['pom.xml', './target/classes'],
  container_selector='workload',
  live_update=[
    sync('./target/classes', '/workspace/BOOT-INF/classes')
  ]
)

k8s_resource('product-service', port_forwards=["8080:8080"],
  extra_pod_selectors=[{'carto.run/workload-name': 'product-service', 'app.kubernetes.io/component':'run'}])

allow_k8s_contexts('educates')