spring:
  cloud.gateway:
    discovery.locator:
      enabled: true
      lowerCaseServiceId: true
      predicates:
      - name: Path
        args:
          pattern: "'/services/'+serviceId+'/**'"
      filters:
      - name: RewritePath
        args:
          regexp: "'/services/' + serviceId + '/?(?<remaining>.*)'"
          replacement: "'/${remaining}'"
    globalcors.corsConfigurations:
      '[/**]':
        allowedOrigins:
          - "*"
        allowedMethods:
          - "*"
        allowedHeaders:
          - "*"    
  codec.max-in-memory-size: -1 # Fix "Exceeded limit on max bytes to buffer" exception for RewriteResponseBodyGatewayFilterFactory
management:
  endpoint:
    restart.enabled: true
    env.show-values: ALWAYS
  endpoints.web.exposure.include: "*"