spring:
  jpa.hibernate.ddl-auto: update
  cache.redis.time-to-live: 60000 # 1 min
  jms.servicebus:
    namespace: ${spring.cloud.azure.servicebus.namespace}
    passwordless-enabled: true
    pricing-tier: basic
    pool: # https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/java/spring-framework/spring-jms-troubleshooting-guide.md#the-messageproducer-was-closed-due-to-an-unrecoverable-error
      enabled: true
      max-connections: 5
  data.redis:
    host: ${spring.redis.host}
    port: ${spring.redis.port}
    password: ${spring.redis.password}
    ssl.enabled: ${spring.redis.ssl}
logging.level.org.springframework.cache: TRACE
management:
  endpoint:
    restart.enabled: true
    env.show-values: WHEN_AUTHORIZED
  endpoints.web.exposure.include: "*"
server:
  error:
    include-message: always
order:
  servicebus-fqn: servicebus.windows.net
  delivered-queue-name: order-delivered-queue
  shipping-queue-name: order-shipping-queue
  products-api-url: